nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
  # resources :cats, only: [:index, :show, :create, :edit, :new]
  resources :cat_rental_requests
end

nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

nine_cats/app/models/cat.rb
class Cat < ApplicationRecord
  validates :birth_date, :name, :sex, presence: true
  
  has_many :cat_rental_requests,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy
end

nine_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  include Comparable
  validates :cat_id, :start_date, :end_date, presence: true
  validate :overlapping_requests
  
  
  belongs_to :cat,
  foreign_key: :cat_id,
  class_name: :Cat
  
  def overlapping_requests
    # find rental requests of specific cat_id
      # all of the rental requests / confirmations for specific cat
    # return grayed out dates
    # see if our date overlaps
    our_start = self.start_date
    our_end = self.end_date
    cat = Cat.find(self.cat_id)
    
    cat.cat_rental_requests.each do |request|
      return false if request.start_date.between?(our_start,our_end) || request.end_date.between?(our_start,our_end) 
    end
    #validation passes if there is no overlap
    return true
  end
end

nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat_rental_requests = CatRentalRequest.all
    render :index
  end
  
  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
    render :show
  end
  
  def edit
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    render :edit
  end
  
  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    if @cat_rental_request.update_attributes(cat_rental_request_params)
      render :show
    else
      render :edit
    end
  end
  
  def new
    render :new
  end
  
  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental_request.save
      render :show
    else
      render :new
    end
  end
  
  private
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id,:start_date,:end_date,:status)
  end
end

nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update_attributes(cat_params)
      render :show
    else
      render :edit
    end
  end
  
  def new
    render :new
  end
  
  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render :show
    else
      render :new
    end
  end
  
  private
  def cat_params
    params.require(:cat).permit(:birth_date,:color,:name,:sex,:description)
  end
end

nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

nine_cats/app/views/cat_rental_requests/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_rental_request_url(@cat_rental_request) %>
<% else %>
  <% action_url = cat_rental_requests_url %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
<br>

<% if action == :edit %>
<h2>Cat name: <%= cat_rental_request.cat.name %> </h2>
<% else %>
<label  for="name">Select which cat you want, bro.</label>
<select id="name" name="cat_rental_request[cat_id]">
    <option disabled>-- Select a Cat, yo. --</option>
    <% Cat.all.each do |cat| %>
          <option value="<% cat.id %>"> <%= cat.name %> </option>
    <% end %>
</select>
<% end %>
<br>

<input type="date" name="cat_rental_request[start_date]" value="<%= cat_rental_request.start_date %>">
<input type="date" name="cat_rental_request[end_date]" value="<%= cat_rental_request.end_date %>">
<br>

<input type="submit" value="add to cat rental requests">
</form>

nine_cats/app/views/cat_rental_requests/edit.html.erb
<h1>Edit a cat rental request</h1>

<%= render 'form', cat_rental_request: @cat_rental_request, action: :edit %>

nine_cats/app/views/cat_rental_requests/index.html.erb
<h1>All the cat_rental_requests!</h1>

<ul>
  <% @cat_rental_requests.each do |cat| %>
  <li> <%= cat.cat.name %> </li>
  <li> <%= cat.start_date %> </li>
  <li> <%= cat.end_date %> </li>
  <li> <a href="<%= cat_rental_request_url(cat) %>">Show Cat Rental Request</a> </li>
    <% end %>
</ul>

nine_cats/app/views/cat_rental_requests/new.html.erb
<h1>Create a cat rental request</h1>

<%= render 'form', cat_rental_request: CatRentalRequest.new, action: :new %>

nine_cats/app/views/cat_rental_requests/show.html.erb
<%= stylesheet_link_tag "application.css" %>

<h1>ONE OF THE CatRentalRequests!!!</h1>

<ul>
  <li>
    <%= @cat_rental_request.cat.name %>
  </li>
  <li> <%= @cat_rental_request.start_date %> </li>
  <li> <%= @cat_rental_request.end_date %> </li>
  <li> <%= @cat_rental_request.status %> </li>
  
</ul>

nine_cats/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(@cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
<br>

<input type="text" name="cat[name]" value="<%= cat.name %>">

<br>

<input type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %> ><label for="cat[sex]">M</label> 
<input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>><label for="cat[sex]">F</label> 
<br>
<label  for="color">Color</label>
<select id="color" name="cat[color]">
    <option disabled>-- Select a Color --</option>
    <option value="Brown" <%= cat.color == "Brown" ? "selected" : "" %> >Brown</option>
    <option value="Orange" <%= cat.color == "Orange" ? "selected" : "" %> >Orange</option>
    <option value="Blue" <%= cat.color == "Blue" ? "selected" : "" %> >Blue</option>
</select>

<br>

<input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

<br>
<label for="description">Description</label>
<br>
<textarea name="cat[description]"><%= cat.description %></textarea>

<br>

<input type="submit" value="add_to_cats">
</form>

nine_cats/app/views/cats/edit.html.erb
<h1>Edit a cat</h1>

<%= render 'form', cat: @cat, action: :edit %>

nine_cats/app/views/cats/index.html.erb
<h1>All the cats!</h1>

<ul>
  <% @cats.each do |cat| %>
  <li> <%= cat.name %> </li>
  <li> <a href="<%= cat_url(cat) %>">Show Cat</a> </li>
    <% end %>
</ul>

nine_cats/app/views/cats/new.html.erb
<h1>Create a cat</h1>

<%= render 'form', cat: Cat.new, action: :new %>

nine_cats/app/views/cats/show.html.erb
<%= stylesheet_link_tag "application.css" %>

<h1>ONE OF THE CATS!!!</h1>
<table>
    <thead>
        <tr>
            <th colspan="3"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @cat.color%></td>
            <td><%= @cat.birth_date%></td>
            <td><%= @cat.sex %></td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td><textarea name="description"><%= @cat.description %></textarea></td>
        </tr>
    </tfoot>
</table>

nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>